---
# tasks file for roles/molecule

- name: Install Molecule
  pip:
    name: molecule

- name: Install Python-Vagrant
  pip:
    name: python-vagrant

- name: Install Molecule-Podman
  pip:
    name: molecule-podman

- name: Install Molecule-Vagrant
  pip:
    # v0.6.3 has a bug fixed in https://github.com/apatard/molecule-vagrant/blob/c3ed4d5f0ee892651233b15c5b485d15ee539497/molecule_vagrant/modules/vagrant.py
    name: molecule-vagrant!=0.6.3
