return {
  black = require('./config/efm/black'),
  buf = require('./config/efm/buf'),
  buildifier = require('./config/efm/buildifier'),
  eslint = require('./config/efm/eslint'),
  fixjson = require('./config/efm/fixjson'),
  flake8 = require('./config/efm/flake8'),
  goimports = require('./config/efm/goimports'),
  golint = require('./config/efm/golint'),
  htmllint = require('./config/efm/htmllint'),
  isort = require('./config/efm/isort'),
  jq = require('./config/efm/jq'),
  jsonlint = require('./config/efm/jsonlint'),
  luafmt = require('./config/efm/luafmt'),
  markdownlint = require('./config/efm/markdownlint'),
  misspell = require('./config/efm/misspell'),
  mypy = require('./config/efm/mypy'),
  prettier = require('./config/efm/prettier'),
  shellcheck = require('./config/efm/shellcheck'),
  shfmt = require('./config/efm/shfmt'),
  stylelint = require('./config/efm/stylelint'),
  terraform = require('./config/efm/terraform'),
  vint = require('./config/efm/vint'),
  yamllint = require('./config/efm/yamllint'),
}
