---
dependency:
  name: galaxy
  options:
    # ignore-certs: True
    # ignore-errors: True
    # role-file: requirements.yml
    requirements-file: collections.yml
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    driver: kvm
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: f34-nvim
    box: fedora/34-cloud-base
    raw_config_args:
      - "cpu_mode = 'host-passthrough'"
    memory: 1024
    cpus: 2
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: "'vagrant'"
    provider_options:
      video_type: "'vga'"
    instance_raw_config_args:
      - 'vagrant.plugins = ["vagrant-libvirt"]'
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  #  cleanup: cleanup.yml
  options:
    vvv: yes
    # vault-id: '@$HOME/.ansible/.vault.key'
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
    ansible_connection: smart  # Override the connection: local
  env:
    ANSIBLE_CONFIG: ../../ansible.cfg
    ANSIBLE_ROLES_PATH: "../../roles/"
    ANSIBLE_COLLECTIONS_PATHS: "../../collections"
  log: true
  lint: |
    set -e
    yamllint .
    ansible-lint
    flake8
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
