---
- name: Converge
  hosts: all

  tasks:
    - name: Make sure we have a 'wheel' group
      ansible.builtin.group:
        name: wheel
        state: present

    - name: Add vagrant user to 'wheel' group
      ansible.builtin.user:
        name: 'vagrant'
        groups: wheel
        append: true

    - name: Enable passwordless sudo for 'wheel' group 
      ansible.builtin.copy:
        dest: /etc/sudoers.d/wheel
        content: "%wheel ALL=(ALL) NOPASSWD: ALL\n"
        validate: visudo -cf %s

  roles:
    - name: nodejs
