---
# tasks file for roles/jenkins

- name: install
  become: yes
  import_tasks: install.yml

- name: firewall
  become: yes
  import_tasks: firewall.yml

- name: ssh
  become: yes
  import_tasks: ssh.yml

- name: configure
  become: yes
  import_tasks: configure.yml
