---
# vars file for dzintars.postfix

postfix_config_dir: '/etc/postfix'
postfix_service: 'postfix'
packages:
  redhat:
    - postfix

- name: Copy Postfix config
  template:
    src: "main.cf.j2"
    dest: "{{ postfix_config_dir }}/main.cf"
    owner: "{{ postfix_user }}"
    group: "{{ postfix_group }}"
    mode: '0644'
    validate: haproxy -f %s -c -q
  notify: Restart Postfix

