namespace: oswee
name: general
version: 0.0.1
readme: README.md
authors:
- dzintars (https://github.com/dzintars)
description: Semi-personal collection for Web development environment
license:
- MIT
license_file: ''
tags: [oswee]
dependencies: {}
repository: http://github.com/oswee/ansible
documentation: https://github.com/oswee/ansible/wiki
homepage: http://github.com/oswee/ansible
issues: https://github.com/oswee/ansible/issues
build_ignore: []
