---
# tasks file for roles/dhcp

- name: allowing firewall rules for ports
  ansible.posix.firewalld:
    port: '{{ item }}'
    permanent: yes
    state: enabled
  notify: restart firewalld
  loop:
    - 67/udp      # bootp & DHCP

- name: Add DHCP service to firewall
  ansible.posix.firewalld:
    service: dhcp
    permanent: yes
    state: enabled
  notify: restart firewalld

- name: Deploy dhcpd.conf template
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart dhcpd
