---
# tasks file for roles/dhcp

- name: Install packages
  become: yes
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
  loop:
    # - dhcp
    - dhcp-server
  notify:
    - enable dhcpd
