---
# tasks file for obsidian

- name: Create appimage directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/.local/share/obsidian"
    state: directory
    mode: '755'
    recurse: true

- name: Download Obsidian
  ansible.builtin.get_url:
    url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ obsidian_version }}/Obsidian-{{ obsidian_version }}.AppImage"
    dest: "/home/{{ ansible_user_id }}/.local/share/obsidian"
    mode: u+x

- name: Extract obsidian appimage
  ansible.builtin.shell:
  args:
    cmd: "./Obsidian-{{ obsidian_version }}.AppImage --appimage-extract"
    chdir: "/home/{{ ansible_user_id }}/.local/share/obsidian"

- name: Create obsidian symlink
  # become: true
  ansible.builtin.file:
    src: "/home/{{ ansible_user_id }}/.local/bin/obsidian/squashfs-root/obsidian"
    path: "/home{{ ansible_user_id }}/.local/bin/obsidian"
    state: link
    force: true
