galaxy_info:
  namespace: oswee
  role_name: swaylock-effects
  version: '0.0.1'
  author: 'Dzintars Klavins'
  description: 'Ansible Galaxy role to maintain nvim'
  company: 'Oswee'

  license: 'Apache-2.0'

  min_ansible_version: '2.11'

  platforms:
    - name: Fedora
      versions:
        - 34

  galaxy_tags:
    - 'nvim'
    - 'oswee'
    - 'dzintars'
    - 'fedora'
  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
