---
# systemd file for envoy

- name: Install Envoy Proxy systemd service
  become: true
  ansible.builtin.template:
    src: 'envoy.service.j2'
    dest: '/etc/systemd/system/{{ envoy_service_name }}.service'
    owner: root
    group: root
    mode: '0644'
  notify:
    - Start Envoy Proxy
    - Enable Envoy Proxy
