---
# tasks file for nvim

#- name: Install packages
#  become: true
#  dnf:
#    name: "{{ item }}"
#    state: latest
#  loop:
#    "{{ packages }}"

# - name: Determine if vim plug is installed for neovim
#   stat:
#     path: "$HOME/.local/share/nvim/site/autoload/plug.vim"
#   register: vim_plug
#   ignore_errors: true

- name: Create vim plug directory
  # when: not vim_plug.stat.exists
  file:
    path: "$HOME/.local/share/nvim/site/autoload"
    state: directory
    # owner: "{{ ansible_user_id }}"

- name: Install vim plug
  # when: not vim_plug.stat.exists
  # become: yes
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "$HOME/.local/share/nvim/site/autoload/"
    # owner: "{{ ansible_user_id }}"
    force: yes

- name: Create nvim directory.
  # when: not vim_plug.stat.exists
  file:
    path: "$HOME/.config/nvim"
    state: directory
    # owner: "{{ ansible_user_id }}"

- name: Create Neovim directories.
  # when: not vim_plug.stat.exists
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    # owner: "{{ ansible_user_id }}"
  loop:
    - "$HOME/.config/nvim/autoload"
    - "$HOME/.config/nvim/plugins.d"
    - "$HOME/.config/nvim/plugged"
    - "$HOME/.config/nvim/sessions"
    - "$HOME/.config/nvim/themes"
    - "$HOME/.config/nvim/undodir"
    - "$HOME/.config/yamllint"

- name: Copy configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: "vim-{{ nvim_environment }}/autoload/plug.vim", dest: "$HOME/.config/nvim/autoload/plug.vim" }
    - { src: "vim-{{ nvim_environment }}/plugins.d/01-startify.vim", dest: "$HOME/.config/nvim/plugins.d/01-startify.vim" }
    - { src: "vim-{{ nvim_environment }}/plugins.d/02-airline.vim", dest: "$HOME/.config/nvim/plugins.d/02-airline.vim" }
    - { src: "vim-{{ nvim_environment }}/plugins.d/20-coc.vim", dest: "$HOME/.config/nvim/plugins.d/20-coc.vim" }
    - { src: "vim-{{ nvim_environment }}/plugins.d/30-ale.vim", dest: "$HOME/.config/nvim/plugins.d/30-ale.vim" }
    - { src: "vim-{{ nvim_environment }}/plugins.d/40-nerdtree.vim", dest: "$HOME/.config/nvim/plugins.d/40-nerdtree.vim" }
    - { src: "vim-{{ nvim_environment }}/plugins.d/50-fzf.vim", dest: "$HOME/.config/nvim/plugins.d/50-fzf.vim" }
    - { src: "vim-{{ nvim_environment }}/autocmd.vim", dest: "$HOME/.config/nvim/autocmd.vim" }
    - { src: "vim-{{ nvim_environment }}/coc-settings.json", dest: "$HOME/.config/nvim/coc-settings.json" }
    - { src: "vim-{{ nvim_environment }}/filetype.vim", dest: "$HOME/.config/nvim/filetype.vim" }
    - { src: "vim-{{ nvim_environment }}/funcs.vim", dest: "$HOME/.config/nvim/funcs.vim" }
    - { src: "vim-{{ nvim_environment }}/general.vim", dest: "$HOME/.config/nvim/general.vim" }
    - { src: "vim-{{ nvim_environment }}/init.vim", dest: "$HOME/.config/nvim/init.vim" }
    - { src: "vim-{{ nvim_environment }}/keys.vim", dest: "$HOME/.config/nvim/keys.vim" }
    - { src: "vim-{{ nvim_environment }}/plugins.vim", dest: "$HOME/.config/nvim/plugins.vim" }
    - { src: "vim-{{ nvim_environment }}/settings.vim", dest: "$HOME/.config/nvim/settings.vim" }
    - { src: "vim-{{ nvim_environment }}/gruvbox.vim", dest: "$HOME/.config/nvim/themes/gruvbox.vim" }
    - { src: "vim-{{ nvim_environment }}/base16-gruvbox-dark-hard.vim", dest: "$HOME/.config/nvim/themes/base16-gruvbox-dark-hard.vim" }
    - { src: "vim-{{ nvim_environment }}/yamllint/", dest: "$HOME/.config/yamllint/" }
  notify:
    - vim-plug install

# # Update remote plugins (e.g., deoplete).
# - name: Update remote plugins
#   # become: yes
#   ignore_errors: true
#   raw: nvim "+UpdateRemotePlugins --sync" +qa &>/dev/null
#   changed_when: no

# TODO: I don't think this should be there at all.
- name: Add vim alias
  ansible.builtin.lineinfile:
    path: $HOME/.zshrc
    line: "alias vim='nvim'"
    owner: "{{ ansible_user_id }}"
    regexp: "^alias vim='nvim'$"
    state: present
    insertafter: '^# Aliases'
    # create: True
