---
# tasks file for nvim

- name: Copy Completion plugin configuration files
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ nvim_config_dir }}/{{ item.dest }}/'
    mode: '0644'
  loop:
    - { src: 'lua/modules/completion/', dest: 'lua/modules/completion' }

- name: Include Completion
  ansible.builtin.lineinfile:
    path: '{{ nvim_config_dir }}/init.lua'
    line: "require('modules.completion')"
    regexp: "^require('modules.completion')$"
    state: present
    # insertafter: '^-- Completion'
    create: True
