---
# handlers file for roles/named

- name: start named
  become: yes
  ansible.builtin.systemd:
    name: named
    state: started

- name: enable named
  become: yes
  ansible.builtin.systemd:
    name: named
    enabled: yes

- name: restart named
  become: yes
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: named

# - name: restart firewalld
#   ansible.builtin.systemd:
#     state: restarted
#     daemon_reload: yes
#     name: firewalld

- name: restart NetworkManager
  become: yes
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: NetworkManager
