---
# tasks file for roles/tftp

- name: Install TFTP
  become: yes
  ansible.builtin.dnf:
    name: tftp-server
    state: present

# - name: Install iPXE
#   ansible.builtin.dnf:
#     name: ipxe-bootimgs
#     state: latest

# - name: Remove symlink
#   file:
#     path: /var/lib/tftpboot
#     state: absent

# - name: Create tftpboot directory
#   ansible.builtin.file:
#     path: /var/lib/tftpboot
#     state: directory
#     owner: root
#     group: root
#     mode: '0644'

# - name: Link the image
#   ansible.builtin.file:
#     src: /usr/share/ipxe/undionly.kpxe
#     dest: /var/lib/tftpboot
#     force: yes
#     state: link

- name: Add TFTP service to the firewall
  become: yes
  ansible.posix.firewalld:
    service: tftp
    permanent: yes
    state: enabled
  notify: Restart Firewalld

- name: Start TFTP service
  become: yes
  ansible.builtin.systemd:
    name: tftp
    state: started
    enabled: yes
