---
# handlers file for roles/jenkins

- name: start jenkins
  become: yes
  ansible.builtin.systemd:
    name: "{{ jenkins_service_name }}"
    state: started

- name: enable jenkins
  become: yes
  ansible.builtin.systemd:
    name: "{{ jenkins_service_name }}"
    enabled: yes

- name: restart jenkins
  become: yes
  ansible.builtin.systemd:
    name: "{{ jenkins_service_name }}"
    state: restarted
    daemon_reload: yes

- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted
    daemon_reload: yes
