---
# tasks file for roles/molecule

- name: Install Molecule
  pip:
    name: molecule

- name: Install Python-Vagrant
  pip:
    name: python-vagrant

- name: Install Molecule-Podman
  pip:
    name: molecule-podman

- name: Install Molecule-Vagrant
  pip:
    name: molecule-vagrant
