---
# tasks file for bazel

- name: Add bazel alias to bazelik
  become: true
  ansible.builtin.copy:
    dest: /etc/profile.d/bazelisk.sh
    content: "alias bazel='bazelisk'\n"

# - name: Add bazel alias
#   lineinfile:
#     path: $HOME/.zshrc
#     line: "alias bazel='bazelisk'"
#     owner: "{{ ansible_user_id }}"
#     regexp: "^alias bazel='bazelisk'$"
#     state: present
#     insertafter: '^# Aliases'
#     # create: True
