---
# tasks file for bazel

- name: Download bazelisk
  become: true
  get_url:
    url: "https://github.com/bazelbuild/bazelisk/releases/download/v{{ bazel_bazelisk_version }}/bazelisk-linux-amd64"
    dest: /usr/local/bin/bazelisk
    mode: a+x

# - name: clone bazel-watcher
#   # become: yes
#   git:
#     repo: git@github.com:bazelbuild/bazel-watcher
#     dest: /tmp/bazel-watcher
#     version: master

# - name: build ibazel
#   become: yes
#   command:
#     argv:
#       - bazel
#       - build
#       - //ibazel
#     chdir: /tmp/bazel-watcher/
#     creates: /tmp/bazel-watcher/bazel-bin/ibazel/linux_amd64_pure_stripped

- name: Download ibazel
  become: true
  get_url:
    url: "https://github.com/bazelbuild/bazel-watcher/releases/download/v{{ bazel_ibazel_version }}/ibazel_linux_amd64"
    dest: /usr/local/bin/ibazel
    mode: a+x

- name: Download buildifier
  become: true
  get_url:
    url: "https://github.com/bazelbuild/buildtools/releases/download/{{ bazel_buildifier_version }}/buildifier"
    dest: /usr/local/bin/buildifier
    mode: a+x
