---
# tasks file for roles/obsidian

- name: Create appimage directory
  # become: yes
  file:
    path: "/home/{{ become_user }}/.local/bin/obsidian"
    state: directory
    mode: '755'
    recurse: yes

- name: Download obsiadian
  get_url:
    url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ obsidian_version }}/Obsidian-{{ obsidian_version }}.AppImage"
    dest: "/home/{{ become_user }}/.local/bin/obsidian"
    mode: u+x

- name: Extract obsidian appimage
  # become: yes
  shell:
  args:
    cmd: "./Obsidian-{{ obsidian_version }}.AppImage --appimage-extract"
    chdir: "/home/{{ become_user }}/.local/bin/obsidian"

- name: Create obsidian symlink
  become: yes
  file:
    src: "/home/{{ become_user }}/.local/bin/obsidian/squashfs-root/obsidian"
    path: /usr/local/bin/obsidian
    state: link
    force: yes
