---
# tasks file for roles/jenkins

- name: Install Jenkins repository
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install Jenkins RPM key
  become: yes
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key

- name: Install packages
  become: yes
  dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ packages.redhat }}"

- name: Create Jenkins system group
  become: yes
  group:
    name: "{{ jenkins_group }}"
    state: present
    system: yes

- name: Create Jenkins user
  become: yes
  user:
    name: "{{ jenkins_user }}"
    home: "{{ jenkins_home }}"
    system: yes
    shell: /bin/false  # TODO: Does this will allow to execute SSH Cert rotation?
    group: "{{ jenkins_group }}"

# TODO: Add the Jenkins to the libvirt group in order to allow Jenkins to
# create localhost virtual machines.
