---
# tasks file for roles/terraform

- name: Install unzip package
  become: yes
  dnf:
    name: unzip.x86_64
    state: present

- name: Download Terraform '{{ terraform_version }}'
  unarchive:
    src: '{{ terraform_url }}'
    dest: /tmp
    remote_src: yes

- name: Copy Terraform '{{ terraform_version }}' binary
  become: yes
  copy:
    src: /tmp/terraform
    dest: /usr/local/bin
    mode: a+x
