---
# tasks file for haproxy

- name: Install
  import_tasks: install.yml
  become: yes
  tags:
    - haproxy:setup
    - haproxy:setup:install

- name: Config
  import_tasks: configure.yml
  become: yes
  tags:
    - haproxy:setup
    - haproxy:setup:config

# - name: Destroy
#   import_tasks: destroy.yml
#   tags:
#     - haproxy:destroy
