---

collections:
  # - name: https://github.com/oswee/ansible.git
  #   version: master
  #   type: git
  # - name: file:///home/dzintars/code/github.com/oswee/ansible.git
  #   version: master
  #   type: git
  - name: oswee.general
