---
# handlers file for install_dhcp

- name: enable dhcpd
  systemd:
    state: enabled
    name: dhcpd

- name: start dhcpd
  systemd:
    state: started
    name: dhcpd

- name: restart dhcpd
  systemd:
    state: restarted
    name: dhcpd

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
