---
# tasks file for roles/minio

- name: Download MinIO Server
  ansible.builtin.get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/minio
    dest: /usr/local/bin
    # owner: "{{ minio_user }}"
    # group: "{{ minio_group }}"
    mode: '0755'

# - name: download MinIO Client
#   get_url:
#     url: https://dl.min.io/client/mc/release/linux-amd64/mc
#     dest: /usr/local/bin
#     owner: "{{ minio_user }}"
#     group: "{{ minio_group }}"
#     mode: '0755'

# - name: Install supplementary packages
#   dnf:
#     name: "{{ item }}"
#     state: present
#   loop: "{{ packages.redhat }}"

- name: Create minio system group
  group:
    name: "{{ minio_group }}"
    state: present
    system: yes

- name: Create minio user
  user:
    name: "{{ minio_user }}"
    system: yes
    shell: /sbin/nologin
    group: "{{ minio_group }}"

- name: Create minio storage and config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: '0755'
  loop:
    - /etc/minio
    - ${HOME}/.minio/certs

- name: Copy minio envirionment variables
  template:
    src: minio.env.j2
    dest: /etc/default/minio
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: '0644'

- name: Copy minio systemd unit file
  template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
    mode: '0644'
  notify:
  - Change user
  - Change group
  - Reexec systemd
  - Start minio
