---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "docker.io/geerlingguy/docker-fedora33-ansible:latest"
    pre_build_image: yes
    command: "/usr/sbin/init"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
provisioner:
  name: ansible
  lint: |
    set -e
    ansible-lint
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
