---
# tasks file for roles/minikube

# - name: Download sha256sum
#   get_url:
#     url: '{{ minikube_mirror }}/{{ minikube_redis_filename }}.sha256'
#     dest: '{{ minikube_download_dir }}/{{ minikube_download_filename }}.sha256'
#     force: no
#     use_proxy: true
#     validate_certs: true
#     mode: 'u=rw,go=r'

# - name: Read sha256sum
#   slurp:
#     src: '{{ minikube_download_dir }}/{{ minikube_download_filename }}.sha256'
#   register: minikube_sha256sum

# - name: Download Minikube
#   get_url:
#     url: '{{ minikube_mirror }}/{{ minikube_redis_filename }}'
#     dest: '{{ minikube_download_dir }}/{{ minikube_download_filename }}'
#     sha256sum: '{{ minikube_sha256sum.content | b64decode | trim }}'
#     force: no
#     use_proxy: true
#     validate_certs: true
#     mode: 'u=rw,go=r'

# - name: Install Minikube
#   become: true
#   copy:
#     src: '{{ minikube_download_dir }}/{{ minikube_download_filename }}'
#     remote_src: true
#     dest: '{{ minikube_install_path }}'
#     force: true
#     owner: root
#     group: root
#     mode: 'u=rwx,go=rx'

- name: Copy Kubernetes repository
  become: true
  copy:
    src: kubernetes.repo
    dest: "/etc/yum.repos.d/kubernetes.repo"
    mode: '0644'

# - name: Update cache centos
#   become: true
#   ansible.builtin.dnf:
#     update_cache: yes

- name: Install Kubectl
  become: true
  ansible.builtin.dnf:
    name: 'kubectl'
    state: present

- name: Install Minikube RPM
  become: true
  ansible.builtin.dnf:
    name: 'https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm'
    state: present
    disable_gpg_check: true
