---
# defaults file for roles/libvirt

libvirt_dir_iso: "/home/{{ become_user }}/kvm/iso"
libvirt_dir_images: "/home/{{ become_user }}/kvm/images"
libvirt_dir_pools: "/home/{{ become_user }}/kvm/pools"
