---
# tasks file for roles/bind

- name: Copy configuration
  become: yes
  ansible.builtin.template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: named
    group: named
    setype: named_conf_t
    mode: '0644'
  notify: restart named

- name: Deploy resolv.conf template
  become: yes
  ansible.builtin.template:
    src: 'resolv.conf.j2'
    dest: /etc/resolv.conf
    setype: named_conf_t
    # owner: root
    # group: root
    mode: 0644
    # backup: yes
  notify:
    - restart NetworkManager

- name: Add an Ethernet connection with static IP configuration
  become: yes
  community.general.nmcli:
    conn_name: eth0
    type: ethernet
    dns4: '{{ network }}.251'
    dns4_search: '{{ cluster_name }}.{{ root_domain }}'
    state: present
  notify:
    - restart NetworkManager

# - name: set qemu user in /etc/sysconfig/network-scripts/ifcfg-enp1s0
#   lineinfile:
#     dest: /etc/sysconfig/network-scripts/ifcfg-enp1s0
#     regexp: "{{ item.pattern }}"
#     line: "{{ item.value }}"
#     state: present
#   loop:
#     - {pattern: '^DNS1=', value: 'DNS1="192.168.1.254"'}
#   notify:
#     - restart NetworkManager
