---
# tasks file for roles/named

- name: install
  import_tasks: install.yml
  tags:
    - named:setup
    - named:setup:install

- name: configure
  import_tasks: configure.yml
  become: yes
  tags:
    - named:setup
    - named:setup:config
