---
# handlers file for roles/dhcpd

- name: start dhcpd
  become: yes
  ansible.builtin.systemd:
    name: dhcpd
    state: started
    enabled: yes

- name: restart dhcpd
  become: yes
  ansible.builtin.systemd:
    name: dhcpd
    state: restarted

- name: enable dhcpd
  become: yes
  ansible.builtin.systemd:
    name: dhcpd
    state: enabled

- name: restart firewalld
  become: yes
  ansible.builtin.service:
    name: firewalld
    state: restarted
