---
# tasks file for roles/matchbox

- name: Install dependencies
  become: yes
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - tar

- name: Download Matchbox
  ansible.builtin.unarchive:
    src: https://github.com/poseidon/matchbox/releases/download/v0.9.0/matchbox-v0.9.0-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy Matchbox binary
  become: yes
  ansible.builtin.copy:
    src: /tmp/matchbox-v0.9.0-linux-amd64/matchbox
    dest: /usr/local/bin
    mode: a+x
    remote_src: yes

- name: Copy Matchbox example systemd unit to allow starting matchbox at boot
  become: yes
  ansible.builtin.copy:
    src: /tmp/matchbox-v0.9.0-linux-amd64/contrib/systemd/matchbox.service
    dest: /etc/systemd/system/matchbox.service
    remote_src: yes
    mode: '0644'

- name: Create Matchbox system group
  become: yes
  ansible.builtin.group:
    name: matchbox
    state: present
    system: yes

- name: Create Matchbox user
  become: yes
  ansible.builtin.user:
    name: matchbox
    system: yes
    group: matchbox

- name: just force systemd to re-execute itself (2.8 and above)
  become: yes
  ansible.builtin.systemd:
    daemon_reexec: yes

- name: Create Matchbox directories
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: matchbox
    group: matchbox
    mode: '0755'
  loop:
    - /etc/matchbox
    - /var/lib/matchbox/assets
    - /var/lib/matchbox/groups
    - /var/lib/matchbox/ignition
    - /var/lib/matchbox/profiles

- name: Start Matchbox service
  become: yes
  ansible.builtin.systemd:
    name: matchbox
    state: started
    enabled: yes
