---
# handlers file for nvim

- name: packer complete
  become: false
  ansible.builtin.command: nvim --headless +"autocmd User PackerComplete quitall" +PackerSync
  # ansible.builtin.command: >
  #   nvim --headless
  #   -c 'autocmd User PackerComplete quitall'
  #   -c 'silent! PackerSync'
  #   -c 'silent! TSInstall maintained'
  #   -c 'silent! TSUpdate' &> /dev/null < /dev/tty

- name: packer sync
  ansible.builtin.shell: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

- name: packer install
  become: false
  ansible.builtin.shell: "nvim +Silent +VimEnter +PackerInstall +qall &>/dev/null"

- name: packer update
  become: false
  ansible.builtin.shell: "nvim +Silent +VimEnter +PackerUpdate +qall &>/dev/null"

- name: packer compile
  become: false
  # ansible.builtin.shell: "nvim +Silent +VimEnter +PackerCompile +qall &>/dev/null"
  ansible.builtin.shell: nvim --headless +'PackerCompile' +'qa'
  # nvim -c "PlugInstall" -c ":qa!"
