---
# tasks file for roles/bind

- name: install packages
  become: yes
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - bind
    - bind-utils
    # - bind-chroot
  notify:
    - enable named
    - start named

# - name: Open firewall tcp port
#   ansible.posix.firewalld:
#     port: '{{ item }}'
#     permanent: yes
#     state: enabled
#   loop:
#     - 53/udp
#     - 53/tcp
#   notify: restart firewalld

- name: add DNS service to firewall
  become: yes
  ansible.posix.firewalld:
    service: dns
    permanent: yes
    state: enabled
  notify:
    - restart firewalld
