namespace: oswee
name: desktop
version: 0.0.1
readme: README.md
authors:
- dzintars (https://github.com/dzintars)
description: Semi-personal collection for Linux desktop environment focussed for full-stack Web development
license:
- MIT
license_file: ''
tags: [oswee, linux]
dependencies: {}
repository: http://github.com/oswee/ansible
documentation: https://github.com/oswee/ansible/wiki
homepage: http://github.com/oswee/ansible
issues: https://github.com/oswee/ansible/issues
build_ignore: []
